spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: master
    username: username
    password: password
    slave-list:
      - name: slave_1
        url: slaveDB
      - name: slave_2
        url: slaveDB
    hikari:
      maximum-pool-size: 50

  jpa:
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        hbm2ddl:
          auto: create
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        defer-datasource-initialization: true
        database-platform: org.hibernate.dialect.MySQL8Dialect
        open-in-view: false
        generate-ddl: true

server:
  tomcat:
    max-connections: 2000
    threads:
      max: 50
#      min-spare: 10           # default
#    accept-count: 100         # default
#    connection-timeout: 20000 # default

# 로그 레벨 설정
#logging:
#  level:
#    org.hibernate.SQL: debug
#    org.hibernate.type: trace